spring.application.name=api-gateway

server.port=8080

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=${EUREKA_PREFER_IP:false}

# movie-service
spring.cloud.gateway.server.webflux.routes[0].id=movie-service-route
spring.cloud.gateway.server.webflux.routes[0].uri=lb://movie-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/movies/**

# cinema-service
spring.cloud.gateway.server.webflux.routes[1].id=cinema-service-route
spring.cloud.gateway.server.webflux.routes[1].uri=lb://cinema-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/cinemas/**