spring.application.name=api-gateway

server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.server.webflux.routes[0].id=movie-service-route
spring.cloud.gateway.server.webflux.routes[0].uri=lb://movie-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/movie/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1